name: CI

on: [push]

jobs:
 test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: 12.3
    - name: Test StylableSwiftUI
      shell: bash
      run: |
        cd Example
        set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace StylableSwiftUI.xcworkspace -scheme StylableSwiftUI-Example ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.3' | xcpretty --color
        cd ..
        pod lib lint --allow-warnings
